services:
  postgres-db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet_user
      POSTGRES_PASSWORD: wallet_password
    ports:
      - "5432:5432"
    volumes:
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql # Script inicial
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: